const universities = [
  {
    en: 'Sultan Qaboos University',
    ar: 'جامعة السلطان قابوس',
    lat: 23.5957,
    lon: 58.1778,
  },
  {
    en: 'Military Technical College',
    ar: 'الكلية التقنية العسكرية',
    lat: 23.5923,
    lon: 58.2843,
  },
  {
    en: 'College of Shariaa Science',
    ar: 'كلية العلوم الشرعية',
    lat: 23.6127,
    lon: 58.2111,
  },
  {
    en: 'Directorate of External Scholarships',
    ar: 'مديرية البعثات الخارجية',
    lat: 23.588,
    lon: 58.285,
  },
  {
    en: 'Directorate of Internal Scholarships',
    ar: 'مديرية البعثات الداخلية',
    lat: 23.589,
    lon: 58.2855,
  },
  {
    en: "A'Seeb Vocational College",
    ar: 'كلية السيب المهنية',
    lat: 23.6703,
    lon: 58.1889,
  },
  {
    en: 'Saham Vocational College',
    ar: 'كلية صحم المهنية',
    lat: 24.1721,
    lon: 56.8862,
  },
  {
    en: 'Ibri Vocational College',
    ar: 'كلية عبري المهنية',
    lat: 23.2155,
    lon: 56.5177,
  },
  {
    en: 'Sur Vocational College',
    ar: 'كلية صور المهنية',
    lat: 22.5667,
    lon: 59.5289,
  },
  {
    en: 'Shinas Vocational College',
    ar: 'كلية شناص المهنية',
    lat: 24.7421,
    lon: 56.4658,
  },
  {
    en: 'Al-Buraimi Vocational College',
    ar: 'كلية البريمي المهنية',
    lat: 24.2516,
    lon: 55.7529,
  },
  {
    en: 'Al-Khabourah Vocational College for Marine Sciences',
    ar: 'كلية الخابورة المهنية للعلوم البحرية',
    lat: 23.9763,
    lon: 57.0949,
  },
  {
    en: 'University of Technology and Applied Sciences - Rustaq',
    ar: 'جامعة التقنية والعلوم التطبيقية - الرستاق',
    lat: 23.3907,
    lon: 57.4244,
  },
  {
    en: 'University of Technology and Applied Sciences - Suhar',
    ar: 'جامعة التقنية والعلوم التطبيقية - صحار',
    lat: 24.3473,
    lon: 56.7456,
  },
  {
    en: 'University of Technology and Applied Sciences - Nizwa',
    ar: 'جامعة التقنية والعلوم التطبيقية - نزوى',
    lat: 22.9333,
    lon: 57.5333,
  },
  {
    en: 'University of Technology and Applied Sciences - Ibri',
    ar: 'جامعة التقنية والعلوم التطبيقية - عبري',
    lat: 23.2249,
    lon: 56.5159,
  },
  {
    en: 'University of Technology and Applied Sciences - Sur',
    ar: 'جامعة التقنية والعلوم التطبيقية - صور',
    lat: 22.5667,
    lon: 59.5289,
  },
  {
    en: 'University of Technology and Applied Sciences - Salalah',
    ar: 'جامعة التقنية والعلوم التطبيقية - صلالة',
    lat: 17.0151,
    lon: 54.0924,
  },
  {
    en: 'University of Technology and Applied Sciences - Muscat',
    ar: 'جامعة التقنية والعلوم التطبيقية - مسقط',
    lat: 23.61,
    lon: 58.54,
  },
  {
    en: "University of Technology and Applied Sciences - Musun'ah",
    ar: 'جامعة التقنية والعلوم التطبيقية - المصنعة',
    lat: 23.7613,
    lon: 57.5512,
  },
  {
    en: 'University of Technology and Applied Sciences - Shinas',
    ar: 'جامعة التقنية والعلوم التطبيقية - شناص',
    lat: 24.7421,
    lon: 56.4658,
  },
  {
    en: 'University of Technology and Applied Sciences - Ibraa',
    ar: 'جامعة التقنية والعلوم التطبيقية - إبراء',
    lat: 22.7415,
    lon: 58.5356,
  },
  {
    en: 'Health Science Institute',
    ar: 'معهد العلوم الصحية',
    lat: 23.5907,
    lon: 58.4148,
  },
  {
    en: 'Pharmacy',
    ar: 'كلية الصيدلة',
    lat: 23.5917,
    lon: 58.4158,
  },
  {
    en: 'Nursing - Muscat Branch',
    ar: 'التمريض - فرع مسقط',
    lat: 23.5927,
    lon: 58.4168,
  },
  {
    en: 'Nursing - South Batinah Branch',
    ar: 'التمريض - فرع جنوب الباطنة',
    lat: 23.3907,
    lon: 57.4244,
  },
  {
    en: 'Nursing - North Batinah Branch',
    ar: 'التمريض - فرع شمال الباطنة',
    lat: 24.3473,
    lon: 56.7456,
  },
  {
    en: 'Nursing - Dakhiliya Branch',
    ar: 'التمريض - فرع الداخلية',
    lat: 22.9333,
    lon: 57.5333,
  },
  {
    en: 'Nursing - Al Dhahirah Branch',
    ar: 'التمريض - فرع الظاهرة',
    lat: 23.2,
    lon: 56.5,
  },
  {
    en: 'Nursing - Ibraa Branch',
    ar: 'التمريض - فرع إبراء',
    lat: 22.7415,
    lon: 58.5356,
  },
  {
    en: 'Nursing - South Shargiya Branch',
    ar: 'التمريض - فرع جنوب الشرقية',
    lat: 22.5667,
    lon: 59.5289,
  },
  {
    en: 'Nursing - Dhofar Branch',
    ar: 'التمريض - فرع ظفار',
    lat: 17.0151,
    lon: 54.0924,
  },
  {
    en: 'Oman Health Information Management Institute',
    ar: 'معهد عمان لإدارة المعلومات الصحية',
    lat: 23.61,
    lon: 58.54,
  },
  {
    en: 'College of Banking and Financial Studies',
    ar: 'كلية الدراسات المصرفية والمالية',
    lat: 23.5822,
    lon: 58.4,
  },
  {
    en: 'Suhar University',
    ar: 'جامعة صحار',
    lat: 24.3473,
    lon: 56.7456,
  },
  {
    en: 'Majan University College',
    ar: 'كلية مجان الجامعية',
    lat: 23.595,
    lon: 58.4508,
  },
  {
    en: 'National University of Science & Technology',
    ar: 'الجامعة الوطنية للعلوم والتكنولوجيا',
    lat: 23.5923,
    lon: 58.2843,
  },
  {
    en: 'Mazoon College',
    ar: 'كلية مزون',
    lat: 23.5913,
    lon: 58.2853,
  },
  {
    en: 'Sur University College',
    ar: 'كلية صور الجامعية',
    lat: 22.5667,
    lon: 59.5289,
  },
  {
    en: 'Middle East College',
    ar: 'كلية الشرق الأوسط',
    lat: 23.5968,
    lon: 58.1778,
  },
  {
    en: 'Al Buraimi University College',
    ar: 'كلية البريمي الجامعية',
    lat: 24.2516,
    lon: 55.7529,
  },
  {
    en: 'Scientific College of Design',
    ar: 'الكلية العلمية للتصميم',
    lat: 23.5933,
    lon: 58.2863,
  },
  {
    en: 'Modern College of Commerce and Science',
    ar: 'الكلية الحديثة للتجارة والعلوم',
    lat: 23.5822,
    lon: 58.4,
  },
  {
    en: 'Oman College Tourism',
    ar: 'كلية عمان للسياحة',
    lat: 23.5943,
    lon: 58.2883,
  },
  {
    en: 'Oman College for Management and Technology',
    ar: 'كلية عمان للإدارة والتكنولوجيا',
    lat: 23.6244,
    lon: 58.0057,
  },
  {
    en: 'Muscat College',
    ar: 'كلية مسقط',
    lat: 23.5832,
    lon: 58.401,
  },
  {
    en: 'International College of Engineering & Management',
    ar: 'الكلية الدولية للهندسة والإدارة',
    lat: 23.5953,
    lon: 58.2893,
  },
  {
    en: 'National College of Automotive Technology',
    ar: 'الكلية الوطنية لتكنولوجيا السيارات',
    lat: 23.5577,
    lon: 58.1951,
  },
  {
    en: 'Dhofar University',
    ar: 'جامعة ظفار',
    lat: 17.0151,
    lon: 54.0924,
  },
  {
    en: 'Gulf College',
    ar: 'كلية الخليج',
    lat: 23.5587,
    lon: 58.1961,
  },
  {
    en: 'National University of Science Technology',
    ar: 'الجامعة الوطنية للعلوم والتكنولوجيا',
    lat: 24.3483,
    lon: 56.7466,
  },
  {
    en: 'Al Bayan College',
    ar: 'كلية البيان',
    lat: 23.6244,
    lon: 58.0057,
  },
  {
    en: 'Arab Open University',
    ar: 'الجامعة العربية المفتوحة',
    lat: 23.5597,
    lon: 58.1971,
  },
  {
    en: "A'Sharqiyah University",
    ar: 'جامعة الشرقية',
    lat: 22.691,
    lon: 58.5469,
  },
  {
    en: 'University of Buraimi',
    ar: 'جامعة البريمي',
    lat: 24.2526,
    lon: 55.7539,
  },
  {
    en: 'Global College of Engineering and Technology',
    ar: 'الكلية العالمية للهندسة والتكنولوجيا',
    lat: 23.5842,
    lon: 58.402,
  },
  {
    en: 'Nizwa University',
    ar: 'جامعة نزوى',
    lat: 22.9343,
    lon: 57.5343,
  },
  {
    en: 'German University of Technology',
    ar: 'الجامعة الألمانية للتكنولوجيا',
    lat: 23.6254,
    lon: 58.0067,
  },
  {
    en: 'Oman Medical College',
    ar: 'كلية عمان الطبية',
    lat: 23.5979,
    lon: 58.4251,
  },
  {
    en: 'Muscat University',
    ar: 'جامعة مسقط',
    lat: 23.6028,
    lon: 58.2888,
  },
];

export const universitiesData = universities.sort((a, b) =>
  a.en.localeCompare(b.en)
);
